//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.17929
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Xml.Serialization;

// 
// This source code was auto-generated by xsd, Version=4.0.30319.17929.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class Term {
    
    private UsedByTerm[] usedByTermField;
    
    private UsesTerm[] usesTermField;
    
    private UsedByFact[] usedByFactField;
    
    private UsedByNeighborhood[] usedByNeighborhoodField;
    
    private UsedByRule[] usedByRuleField;
    
    private DerivedByRule[] derivedByRuleField;
    
    private UsedByDecisionTable[] usedByDecisionTableField;
    
    private UsedByDecision[] usedByDecisionField;
    
    private DerivedByDecision[] derivedByDecisionField;
    
    private DerivedByDecisionTable[] derivedByDecisionTableField;
    
    private AppliesToDecision[] appliesToDecisionField;
    
    private ItemProperties[] itemPropertiesField;
    
    private TermDefinition[] definitionField;
    
    private string showField;
    
    private string displayModeField;
    
    private string idField;
    
    private string signifierField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("UsedByTerm")]
    public UsedByTerm[] UsedByTerm {
        get {
            return this.usedByTermField;
        }
        set {
            this.usedByTermField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("UsesTerm")]
    public UsesTerm[] UsesTerm {
        get {
            return this.usesTermField;
        }
        set {
            this.usesTermField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("UsedByFact")]
    public UsedByFact[] UsedByFact {
        get {
            return this.usedByFactField;
        }
        set {
            this.usedByFactField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("UsedByNeighborhood")]
    public UsedByNeighborhood[] UsedByNeighborhood {
        get {
            return this.usedByNeighborhoodField;
        }
        set {
            this.usedByNeighborhoodField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("UsedByRule")]
    public UsedByRule[] UsedByRule {
        get {
            return this.usedByRuleField;
        }
        set {
            this.usedByRuleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("DerivedByRule")]
    public DerivedByRule[] DerivedByRule {
        get {
            return this.derivedByRuleField;
        }
        set {
            this.derivedByRuleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("UsedByDecisionTable")]
    public UsedByDecisionTable[] UsedByDecisionTable {
        get {
            return this.usedByDecisionTableField;
        }
        set {
            this.usedByDecisionTableField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("UsedByDecision")]
    public UsedByDecision[] UsedByDecision {
        get {
            return this.usedByDecisionField;
        }
        set {
            this.usedByDecisionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("DerivedByDecision")]
    public DerivedByDecision[] DerivedByDecision {
        get {
            return this.derivedByDecisionField;
        }
        set {
            this.derivedByDecisionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("DerivedByDecisionTable")]
    public DerivedByDecisionTable[] DerivedByDecisionTable {
        get {
            return this.derivedByDecisionTableField;
        }
        set {
            this.derivedByDecisionTableField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("AppliesToDecision")]
    public AppliesToDecision[] AppliesToDecision {
        get {
            return this.appliesToDecisionField;
        }
        set {
            this.appliesToDecisionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ItemProperties")]
    public ItemProperties[] ItemProperties {
        get {
            return this.itemPropertiesField;
        }
        set {
            this.itemPropertiesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Definition", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public TermDefinition[] Definition {
        get {
            return this.definitionField;
        }
        set {
            this.definitionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string show {
        get {
            return this.showField;
        }
        set {
            this.showField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string displayMode {
        get {
            return this.displayModeField;
        }
        set {
            this.displayModeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ID {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string signifier {
        get {
            return this.signifierField;
        }
        set {
            this.signifierField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class UsedByTerm {
    
    private string showField;
    
    private string displayModeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string show {
        get {
            return this.showField;
        }
        set {
            this.showField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string displayMode {
        get {
            return this.displayModeField;
        }
        set {
            this.displayModeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class UsesTerm {
    
    private string showField;
    
    private string displayModeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string show {
        get {
            return this.showField;
        }
        set {
            this.showField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string displayMode {
        get {
            return this.displayModeField;
        }
        set {
            this.displayModeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class UsedByFact {
    
    private string showField;
    
    private string displayModeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string show {
        get {
            return this.showField;
        }
        set {
            this.showField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string displayMode {
        get {
            return this.displayModeField;
        }
        set {
            this.displayModeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class UsedByNeighborhood {
    
    private string showField;
    
    private string displayModeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string show {
        get {
            return this.showField;
        }
        set {
            this.showField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string displayMode {
        get {
            return this.displayModeField;
        }
        set {
            this.displayModeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class UsedByRule {
    
    private string showField;
    
    private string displayModeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string show {
        get {
            return this.showField;
        }
        set {
            this.showField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string displayMode {
        get {
            return this.displayModeField;
        }
        set {
            this.displayModeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class DerivedByRule {
    
    private string showField;
    
    private string displayModeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string show {
        get {
            return this.showField;
        }
        set {
            this.showField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string displayMode {
        get {
            return this.displayModeField;
        }
        set {
            this.displayModeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class UsedByDecisionTable {
    
    private string showField;
    
    private string displayModeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string show {
        get {
            return this.showField;
        }
        set {
            this.showField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string displayMode {
        get {
            return this.displayModeField;
        }
        set {
            this.displayModeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class UsedByDecision {
    
    private string showField;
    
    private string displayModeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string show {
        get {
            return this.showField;
        }
        set {
            this.showField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string displayMode {
        get {
            return this.displayModeField;
        }
        set {
            this.displayModeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class DerivedByDecision {
    
    private string showField;
    
    private string displayModeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string show {
        get {
            return this.showField;
        }
        set {
            this.showField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string displayMode {
        get {
            return this.displayModeField;
        }
        set {
            this.displayModeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class DerivedByDecisionTable {
    
    private string showField;
    
    private string displayModeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string show {
        get {
            return this.showField;
        }
        set {
            this.showField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string displayMode {
        get {
            return this.displayModeField;
        }
        set {
            this.displayModeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class AppliesToDecision {
    
    private string showField;
    
    private string displayModeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string show {
        get {
            return this.showField;
        }
        set {
            this.showField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string displayMode {
        get {
            return this.displayModeField;
        }
        set {
            this.displayModeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class ItemProperties {
    
    private string groupNameField;
    
    private ItemPropertiesItemProperty[] itemPropertyField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string GroupName {
        get {
            return this.groupNameField;
        }
        set {
            this.groupNameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ItemProperty", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public ItemPropertiesItemProperty[] ItemProperty {
        get {
            return this.itemPropertyField;
        }
        set {
            this.itemPropertyField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ItemPropertiesItemProperty {
    
    private string nameField;
    
    private ItemPropertiesItemPropertyValue[] valueField;
    
    private string conceptIDField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Name {
        get {
            return this.nameField;
        }
        set {
            this.nameField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Value", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public ItemPropertiesItemPropertyValue[] Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ConceptID {
        get {
            return this.conceptIDField;
        }
        set {
            this.conceptIDField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class ItemPropertiesItemPropertyValue {
    
    private string textField;
    
    private string strValField;
    
    private string propertyValueIDField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string Text {
        get {
            return this.textField;
        }
        set {
            this.textField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string StrVal {
        get {
            return this.strValField;
        }
        set {
            this.strValField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string PropertyValueID {
        get {
            return this.propertyValueIDField;
        }
        set {
            this.propertyValueIDField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class TermDefinition {
    
    private Text[] textField;
    
    private TermRef[] termRefField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Text", IsNullable=true)]
    public Text[] Text {
        get {
            return this.textField;
        }
        set {
            this.textField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("TermRef", IsNullable=true)]
    public TermRef[] TermRef {
        get {
            return this.termRefField;
        }
        set {
            this.termRefField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=true)]
public partial class Text {
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=true)]
public partial class TermRef {
    
    private string idrefField;
    
    private string valueField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string idref {
        get {
            return this.idrefField;
        }
        set {
            this.idrefField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlTextAttribute()]
    public string Value {
        get {
            return this.valueField;
        }
        set {
            this.valueField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class UsesFactSymbol {
    
    private string showField;
    
    private string displayModeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string show {
        get {
            return this.showField;
        }
        set {
            this.showField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string displayMode {
        get {
            return this.displayModeField;
        }
        set {
            this.displayModeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class Rule {
    
    private UsesTerm[] usesTermField;
    
    private DerivesTerm[] derivesTermField;
    
    private UsesFact[] usesFactField;
    
    private RuleRuleRelation[] ruleRelationField;
    
    private UsedByDecisionTable[] usedByDecisionTableField;
    
    private UsedByRuleGroup[] usedByRuleGroupField;
    
    private UsedByDecision[] usedByDecisionField;
    
    private ItemProperties[] itemPropertiesField;
    
    private RuleStatement[] statementField;
    
    private string showField;
    
    private string displayModeField;
    
    private string idField;
    
    private string signifierField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("UsesTerm")]
    public UsesTerm[] UsesTerm {
        get {
            return this.usesTermField;
        }
        set {
            this.usesTermField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("DerivesTerm")]
    public DerivesTerm[] DerivesTerm {
        get {
            return this.derivesTermField;
        }
        set {
            this.derivesTermField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("UsesFact")]
    public UsesFact[] UsesFact {
        get {
            return this.usesFactField;
        }
        set {
            this.usesFactField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("RuleRelation", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public RuleRuleRelation[] RuleRelation {
        get {
            return this.ruleRelationField;
        }
        set {
            this.ruleRelationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("UsedByDecisionTable")]
    public UsedByDecisionTable[] UsedByDecisionTable {
        get {
            return this.usedByDecisionTableField;
        }
        set {
            this.usedByDecisionTableField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("UsedByRuleGroup")]
    public UsedByRuleGroup[] UsedByRuleGroup {
        get {
            return this.usedByRuleGroupField;
        }
        set {
            this.usedByRuleGroupField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("UsedByDecision")]
    public UsedByDecision[] UsedByDecision {
        get {
            return this.usedByDecisionField;
        }
        set {
            this.usedByDecisionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ItemProperties")]
    public ItemProperties[] ItemProperties {
        get {
            return this.itemPropertiesField;
        }
        set {
            this.itemPropertiesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Statement", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public RuleStatement[] Statement {
        get {
            return this.statementField;
        }
        set {
            this.statementField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string show {
        get {
            return this.showField;
        }
        set {
            this.showField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string displayMode {
        get {
            return this.displayModeField;
        }
        set {
            this.displayModeField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ID {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string signifier {
        get {
            return this.signifierField;
        }
        set {
            this.signifierField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class DerivesTerm {
    
    private string showField;
    
    private string displayModeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string show {
        get {
            return this.showField;
        }
        set {
            this.showField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string displayMode {
        get {
            return this.displayModeField;
        }
        set {
            this.displayModeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class UsesFact {
    
    private string showField;
    
    private string displayModeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string show {
        get {
            return this.showField;
        }
        set {
            this.showField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string displayMode {
        get {
            return this.displayModeField;
        }
        set {
            this.displayModeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class RuleRuleRelation {
    
    private string showField;
    
    private string displayModeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string show {
        get {
            return this.showField;
        }
        set {
            this.showField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string displayMode {
        get {
            return this.displayModeField;
        }
        set {
            this.displayModeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class UsedByRuleGroup {
    
    private string showField;
    
    private string displayModeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string show {
        get {
            return this.showField;
        }
        set {
            this.showField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string displayMode {
        get {
            return this.displayModeField;
        }
        set {
            this.displayModeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class RuleStatement {
    
    private Text[] textField;
    
    private TermRef[] termRefField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Text", IsNullable=true)]
    public Text[] Text {
        get {
            return this.textField;
        }
        set {
            this.textField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("TermRef", IsNullable=true)]
    public TermRef[] TermRef {
        get {
            return this.termRefField;
        }
        set {
            this.termRefField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class DerivesFact {
    
    private string showField;
    
    private string displayModeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string show {
        get {
            return this.showField;
        }
        set {
            this.showField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string displayMode {
        get {
            return this.displayModeField;
        }
        set {
            this.displayModeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class UsesDecisionTable {
    
    private string showField;
    
    private string displayModeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string show {
        get {
            return this.showField;
        }
        set {
            this.showField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string displayMode {
        get {
            return this.displayModeField;
        }
        set {
            this.displayModeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class UsesRule {
    
    private string showField;
    
    private string displayModeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string show {
        get {
            return this.showField;
        }
        set {
            this.showField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string displayMode {
        get {
            return this.displayModeField;
        }
        set {
            this.displayModeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class UsesRuleGroup {
    
    private string showField;
    
    private string displayModeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string show {
        get {
            return this.showField;
        }
        set {
            this.showField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string displayMode {
        get {
            return this.displayModeField;
        }
        set {
            this.displayModeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class RuleXpressPublication {
    
    private string appliedFilterField;
    
    private RuleXpressPublicationLayout[] layoutField;
    
    private RuleXpressPublicationContent[] contentField;
    
    private string languageField;
    
    private string reportdateField;
    
    private string reportmemberField;
    
    private string titleField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string AppliedFilter {
        get {
            return this.appliedFilterField;
        }
        set {
            this.appliedFilterField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Layout", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public RuleXpressPublicationLayout[] Layout {
        get {
            return this.layoutField;
        }
        set {
            this.layoutField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Content", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public RuleXpressPublicationContent[] Content {
        get {
            return this.contentField;
        }
        set {
            this.contentField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string language {
        get {
            return this.languageField;
        }
        set {
            this.languageField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string reportdate {
        get {
            return this.reportdateField;
        }
        set {
            this.reportdateField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string reportmember {
        get {
            return this.reportmemberField;
        }
        set {
            this.reportmemberField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string title {
        get {
            return this.titleField;
        }
        set {
            this.titleField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class RuleXpressPublicationLayout {
    
    private RuleXpressPublicationLayoutDocument[] documentField;
    
    private RuleXpressPublicationLayoutHeader[] headerField;
    
    private RuleXpressPublicationLayoutItem[] itemField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Document", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public RuleXpressPublicationLayoutDocument[] Document {
        get {
            return this.documentField;
        }
        set {
            this.documentField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Header", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public RuleXpressPublicationLayoutHeader[] Header {
        get {
            return this.headerField;
        }
        set {
            this.headerField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Item", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public RuleXpressPublicationLayoutItem[] Item {
        get {
            return this.itemField;
        }
        set {
            this.itemField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class RuleXpressPublicationLayoutDocument {
    
    private RuleXpressPublicationLayoutDocumentEmptyProperties[] emptyPropertiesField;
    
    private RuleXpressPublicationLayoutDocumentInternalId[] internalIdField;
    
    private string orientationField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("EmptyProperties", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public RuleXpressPublicationLayoutDocumentEmptyProperties[] EmptyProperties {
        get {
            return this.emptyPropertiesField;
        }
        set {
            this.emptyPropertiesField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("InternalId", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public RuleXpressPublicationLayoutDocumentInternalId[] InternalId {
        get {
            return this.internalIdField;
        }
        set {
            this.internalIdField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string orientation {
        get {
            return this.orientationField;
        }
        set {
            this.orientationField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class RuleXpressPublicationLayoutDocumentEmptyProperties {
    
    private string showField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string show {
        get {
            return this.showField;
        }
        set {
            this.showField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class RuleXpressPublicationLayoutDocumentInternalId {
    
    private string showField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string show {
        get {
            return this.showField;
        }
        set {
            this.showField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class RuleXpressPublicationLayoutHeader {
    
    private RuleXpressPublicationLayoutHeaderShortcutList[] shortcutListField;
    
    private RuleXpressPublicationLayoutHeaderAppliedFilters[] appliedFiltersField;
    
    private RuleXpressPublicationLayoutHeaderGeneralInformation[] generalInformationField;
    
    private string showField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ShortcutList", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public RuleXpressPublicationLayoutHeaderShortcutList[] ShortcutList {
        get {
            return this.shortcutListField;
        }
        set {
            this.shortcutListField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("AppliedFilters", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public RuleXpressPublicationLayoutHeaderAppliedFilters[] AppliedFilters {
        get {
            return this.appliedFiltersField;
        }
        set {
            this.appliedFiltersField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("GeneralInformation", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public RuleXpressPublicationLayoutHeaderGeneralInformation[] GeneralInformation {
        get {
            return this.generalInformationField;
        }
        set {
            this.generalInformationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string show {
        get {
            return this.showField;
        }
        set {
            this.showField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class RuleXpressPublicationLayoutHeaderShortcutList {
    
    private string showField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string show {
        get {
            return this.showField;
        }
        set {
            this.showField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class RuleXpressPublicationLayoutHeaderAppliedFilters {
    
    private string showField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string show {
        get {
            return this.showField;
        }
        set {
            this.showField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class RuleXpressPublicationLayoutHeaderGeneralInformation {
    
    private string showField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string show {
        get {
            return this.showField;
        }
        set {
            this.showField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class RuleXpressPublicationLayoutItem {
    
    private Term[] termField;
    
    private RuleXpressPublicationLayoutItemFact[] factField;
    
    private RuleXpressPublicationLayoutItemFactSymbol[] factSymbolField;
    
    private RuleXpressPublicationLayoutItemNeighborhood[] neighborhoodField;
    
    private Rule[] ruleField;
    
    private RuleXpressPublicationLayoutItemDecisionTable[] decisionTableField;
    
    private RuleXpressPublicationLayoutItemRuleGroup[] ruleGroupField;
    
    private RuleXpressPublicationLayoutItemDecision[] decisionField;
    
    private RuleXpressPublicationLayoutItemQualityItem[] qualityItemField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Term")]
    public Term[] Term {
        get {
            return this.termField;
        }
        set {
            this.termField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Fact", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public RuleXpressPublicationLayoutItemFact[] Fact {
        get {
            return this.factField;
        }
        set {
            this.factField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("FactSymbol", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public RuleXpressPublicationLayoutItemFactSymbol[] FactSymbol {
        get {
            return this.factSymbolField;
        }
        set {
            this.factSymbolField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Neighborhood", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public RuleXpressPublicationLayoutItemNeighborhood[] Neighborhood {
        get {
            return this.neighborhoodField;
        }
        set {
            this.neighborhoodField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Rule")]
    public Rule[] Rule {
        get {
            return this.ruleField;
        }
        set {
            this.ruleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("DecisionTable", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public RuleXpressPublicationLayoutItemDecisionTable[] DecisionTable {
        get {
            return this.decisionTableField;
        }
        set {
            this.decisionTableField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("RuleGroup", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public RuleXpressPublicationLayoutItemRuleGroup[] RuleGroup {
        get {
            return this.ruleGroupField;
        }
        set {
            this.ruleGroupField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Decision", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public RuleXpressPublicationLayoutItemDecision[] Decision {
        get {
            return this.decisionField;
        }
        set {
            this.decisionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("QualityItem", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public RuleXpressPublicationLayoutItemQualityItem[] QualityItem {
        get {
            return this.qualityItemField;
        }
        set {
            this.qualityItemField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class RuleXpressPublicationLayoutItemFact {
    
    private UsedByTerm[] usedByTermField;
    
    private UsesTerm[] usesTermField;
    
    private UsesFactSymbol[] usesFactSymbolField;
    
    private UsedByNeighborhood[] usedByNeighborhoodField;
    
    private UsedByRule[] usedByRuleField;
    
    private UsedByDecisionTable[] usedByDecisionTableField;
    
    private DerivedByRule[] derivedByRuleField;
    
    private DerivedByDecisionTable[] derivedByDecisionTableField;
    
    private UsedByDecision[] usedByDecisionField;
    
    private DerivedByDecision[] derivedByDecisionField;
    
    private AppliesToDecision[] appliesToDecisionField;
    
    private string showField;
    
    private string displayModeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("UsedByTerm")]
    public UsedByTerm[] UsedByTerm {
        get {
            return this.usedByTermField;
        }
        set {
            this.usedByTermField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("UsesTerm")]
    public UsesTerm[] UsesTerm {
        get {
            return this.usesTermField;
        }
        set {
            this.usesTermField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("UsesFactSymbol")]
    public UsesFactSymbol[] UsesFactSymbol {
        get {
            return this.usesFactSymbolField;
        }
        set {
            this.usesFactSymbolField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("UsedByNeighborhood")]
    public UsedByNeighborhood[] UsedByNeighborhood {
        get {
            return this.usedByNeighborhoodField;
        }
        set {
            this.usedByNeighborhoodField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("UsedByRule")]
    public UsedByRule[] UsedByRule {
        get {
            return this.usedByRuleField;
        }
        set {
            this.usedByRuleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("UsedByDecisionTable")]
    public UsedByDecisionTable[] UsedByDecisionTable {
        get {
            return this.usedByDecisionTableField;
        }
        set {
            this.usedByDecisionTableField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("DerivedByRule")]
    public DerivedByRule[] DerivedByRule {
        get {
            return this.derivedByRuleField;
        }
        set {
            this.derivedByRuleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("DerivedByDecisionTable")]
    public DerivedByDecisionTable[] DerivedByDecisionTable {
        get {
            return this.derivedByDecisionTableField;
        }
        set {
            this.derivedByDecisionTableField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("UsedByDecision")]
    public UsedByDecision[] UsedByDecision {
        get {
            return this.usedByDecisionField;
        }
        set {
            this.usedByDecisionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("DerivedByDecision")]
    public DerivedByDecision[] DerivedByDecision {
        get {
            return this.derivedByDecisionField;
        }
        set {
            this.derivedByDecisionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("AppliesToDecision")]
    public AppliesToDecision[] AppliesToDecision {
        get {
            return this.appliesToDecisionField;
        }
        set {
            this.appliesToDecisionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string show {
        get {
            return this.showField;
        }
        set {
            this.showField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string displayMode {
        get {
            return this.displayModeField;
        }
        set {
            this.displayModeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class RuleXpressPublicationLayoutItemFactSymbol {
    
    private UsedByFact[] usedByFactField;
    
    private UsedByNeighborhood[] usedByNeighborhoodField;
    
    private string showField;
    
    private string displayModeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("UsedByFact")]
    public UsedByFact[] UsedByFact {
        get {
            return this.usedByFactField;
        }
        set {
            this.usedByFactField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("UsedByNeighborhood")]
    public UsedByNeighborhood[] UsedByNeighborhood {
        get {
            return this.usedByNeighborhoodField;
        }
        set {
            this.usedByNeighborhoodField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string show {
        get {
            return this.showField;
        }
        set {
            this.showField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string displayMode {
        get {
            return this.displayModeField;
        }
        set {
            this.displayModeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class RuleXpressPublicationLayoutItemNeighborhood {
    
    private UsesTerm[] usesTermField;
    
    private UsedByFact[] usedByFactField;
    
    private UsesFactSymbol[] usesFactSymbolField;
    
    private string showField;
    
    private string displayModeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("UsesTerm")]
    public UsesTerm[] UsesTerm {
        get {
            return this.usesTermField;
        }
        set {
            this.usesTermField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("UsedByFact")]
    public UsedByFact[] UsedByFact {
        get {
            return this.usedByFactField;
        }
        set {
            this.usedByFactField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("UsesFactSymbol")]
    public UsesFactSymbol[] UsesFactSymbol {
        get {
            return this.usesFactSymbolField;
        }
        set {
            this.usesFactSymbolField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string show {
        get {
            return this.showField;
        }
        set {
            this.showField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string displayMode {
        get {
            return this.displayModeField;
        }
        set {
            this.displayModeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class RuleXpressPublicationLayoutItemDecisionTable {
    
    private UsesTerm[] usesTermField;
    
    private UsesFact[] usesFactField;
    
    private DerivesTerm[] derivesTermField;
    
    private DerivesFact[] derivesFactField;
    
    private UsedByDecisionTable[] usedByDecisionTableField;
    
    private UsesDecisionTable[] usesDecisionTableField;
    
    private UsedByRuleGroup[] usedByRuleGroupField;
    
    private UsedByDecision[] usedByDecisionField;
    
    private string showField;
    
    private string displayModeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("UsesTerm")]
    public UsesTerm[] UsesTerm {
        get {
            return this.usesTermField;
        }
        set {
            this.usesTermField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("UsesFact")]
    public UsesFact[] UsesFact {
        get {
            return this.usesFactField;
        }
        set {
            this.usesFactField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("DerivesTerm")]
    public DerivesTerm[] DerivesTerm {
        get {
            return this.derivesTermField;
        }
        set {
            this.derivesTermField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("DerivesFact")]
    public DerivesFact[] DerivesFact {
        get {
            return this.derivesFactField;
        }
        set {
            this.derivesFactField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("UsedByDecisionTable")]
    public UsedByDecisionTable[] UsedByDecisionTable {
        get {
            return this.usedByDecisionTableField;
        }
        set {
            this.usedByDecisionTableField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("UsesDecisionTable")]
    public UsesDecisionTable[] UsesDecisionTable {
        get {
            return this.usesDecisionTableField;
        }
        set {
            this.usesDecisionTableField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("UsedByRuleGroup")]
    public UsedByRuleGroup[] UsedByRuleGroup {
        get {
            return this.usedByRuleGroupField;
        }
        set {
            this.usedByRuleGroupField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("UsedByDecision")]
    public UsedByDecision[] UsedByDecision {
        get {
            return this.usedByDecisionField;
        }
        set {
            this.usedByDecisionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string show {
        get {
            return this.showField;
        }
        set {
            this.showField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string displayMode {
        get {
            return this.displayModeField;
        }
        set {
            this.displayModeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class RuleXpressPublicationLayoutItemRuleGroup {
    
    private UsesRule[] usesRuleField;
    
    private UsesDecisionTable[] usesDecisionTableField;
    
    private UsedByRuleGroup[] usedByRuleGroupField;
    
    private UsesRuleGroup[] usesRuleGroupField;
    
    private UsedByDecision[] usedByDecisionField;
    
    private string showField;
    
    private string displayModeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("UsesRule")]
    public UsesRule[] UsesRule {
        get {
            return this.usesRuleField;
        }
        set {
            this.usesRuleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("UsesDecisionTable")]
    public UsesDecisionTable[] UsesDecisionTable {
        get {
            return this.usesDecisionTableField;
        }
        set {
            this.usesDecisionTableField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("UsedByRuleGroup")]
    public UsedByRuleGroup[] UsedByRuleGroup {
        get {
            return this.usedByRuleGroupField;
        }
        set {
            this.usedByRuleGroupField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("UsesRuleGroup")]
    public UsesRuleGroup[] UsesRuleGroup {
        get {
            return this.usesRuleGroupField;
        }
        set {
            this.usesRuleGroupField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("UsedByDecision")]
    public UsedByDecision[] UsedByDecision {
        get {
            return this.usedByDecisionField;
        }
        set {
            this.usedByDecisionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string show {
        get {
            return this.showField;
        }
        set {
            this.showField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string displayMode {
        get {
            return this.displayModeField;
        }
        set {
            this.displayModeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class RuleXpressPublicationLayoutItemDecision {
    
    private UsesTerm[] usesTermField;
    
    private DerivesTerm[] derivesTermField;
    
    private RuleXpressPublicationLayoutItemDecisionBasedOnTerm[] basedOnTermField;
    
    private UsesFact[] usesFactField;
    
    private DerivesFact[] derivesFactField;
    
    private RuleXpressPublicationLayoutItemDecisionBasedOnFact[] basedOnFactField;
    
    private UsesRule[] usesRuleField;
    
    private UsesDecisionTable[] usesDecisionTableField;
    
    private UsesRuleGroup[] usesRuleGroupField;
    
    private RuleXpressPublicationLayoutItemDecisionUsesDecision[] usesDecisionField;
    
    private UsedByDecision[] usedByDecisionField;
    
    private string showField;
    
    private string displayModeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("UsesTerm")]
    public UsesTerm[] UsesTerm {
        get {
            return this.usesTermField;
        }
        set {
            this.usesTermField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("DerivesTerm")]
    public DerivesTerm[] DerivesTerm {
        get {
            return this.derivesTermField;
        }
        set {
            this.derivesTermField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("BasedOnTerm", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public RuleXpressPublicationLayoutItemDecisionBasedOnTerm[] BasedOnTerm {
        get {
            return this.basedOnTermField;
        }
        set {
            this.basedOnTermField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("UsesFact")]
    public UsesFact[] UsesFact {
        get {
            return this.usesFactField;
        }
        set {
            this.usesFactField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("DerivesFact")]
    public DerivesFact[] DerivesFact {
        get {
            return this.derivesFactField;
        }
        set {
            this.derivesFactField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("BasedOnFact", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public RuleXpressPublicationLayoutItemDecisionBasedOnFact[] BasedOnFact {
        get {
            return this.basedOnFactField;
        }
        set {
            this.basedOnFactField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("UsesRule")]
    public UsesRule[] UsesRule {
        get {
            return this.usesRuleField;
        }
        set {
            this.usesRuleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("UsesDecisionTable")]
    public UsesDecisionTable[] UsesDecisionTable {
        get {
            return this.usesDecisionTableField;
        }
        set {
            this.usesDecisionTableField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("UsesRuleGroup")]
    public UsesRuleGroup[] UsesRuleGroup {
        get {
            return this.usesRuleGroupField;
        }
        set {
            this.usesRuleGroupField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("UsesDecision", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public RuleXpressPublicationLayoutItemDecisionUsesDecision[] UsesDecision {
        get {
            return this.usesDecisionField;
        }
        set {
            this.usesDecisionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("UsedByDecision")]
    public UsedByDecision[] UsedByDecision {
        get {
            return this.usedByDecisionField;
        }
        set {
            this.usedByDecisionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string show {
        get {
            return this.showField;
        }
        set {
            this.showField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string displayMode {
        get {
            return this.displayModeField;
        }
        set {
            this.displayModeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class RuleXpressPublicationLayoutItemDecisionBasedOnTerm {
    
    private string showField;
    
    private string displayModeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string show {
        get {
            return this.showField;
        }
        set {
            this.showField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string displayMode {
        get {
            return this.displayModeField;
        }
        set {
            this.displayModeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class RuleXpressPublicationLayoutItemDecisionBasedOnFact {
    
    private string showField;
    
    private string displayModeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string show {
        get {
            return this.showField;
        }
        set {
            this.showField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string displayMode {
        get {
            return this.displayModeField;
        }
        set {
            this.displayModeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class RuleXpressPublicationLayoutItemDecisionUsesDecision {
    
    private string showField;
    
    private string displayModeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string show {
        get {
            return this.showField;
        }
        set {
            this.showField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string displayMode {
        get {
            return this.displayModeField;
        }
        set {
            this.displayModeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class RuleXpressPublicationLayoutItemQualityItem {
    
    private UsedByTerm[] usedByTermField;
    
    private UsedByFact[] usedByFactField;
    
    private RuleXpressPublicationLayoutItemQualityItemUsedByFactSymbol[] usedByFactSymbolField;
    
    private UsedByRule[] usedByRuleField;
    
    private UsedByDecisionTable[] usedByDecisionTableField;
    
    private UsedByRuleGroup[] usedByRuleGroupField;
    
    private UsedByDecision[] usedByDecisionField;
    
    private string showField;
    
    private string displayModeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("UsedByTerm")]
    public UsedByTerm[] UsedByTerm {
        get {
            return this.usedByTermField;
        }
        set {
            this.usedByTermField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("UsedByFact")]
    public UsedByFact[] UsedByFact {
        get {
            return this.usedByFactField;
        }
        set {
            this.usedByFactField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("UsedByFactSymbol", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public RuleXpressPublicationLayoutItemQualityItemUsedByFactSymbol[] UsedByFactSymbol {
        get {
            return this.usedByFactSymbolField;
        }
        set {
            this.usedByFactSymbolField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("UsedByRule")]
    public UsedByRule[] UsedByRule {
        get {
            return this.usedByRuleField;
        }
        set {
            this.usedByRuleField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("UsedByDecisionTable")]
    public UsedByDecisionTable[] UsedByDecisionTable {
        get {
            return this.usedByDecisionTableField;
        }
        set {
            this.usedByDecisionTableField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("UsedByRuleGroup")]
    public UsedByRuleGroup[] UsedByRuleGroup {
        get {
            return this.usedByRuleGroupField;
        }
        set {
            this.usedByRuleGroupField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("UsedByDecision")]
    public UsedByDecision[] UsedByDecision {
        get {
            return this.usedByDecisionField;
        }
        set {
            this.usedByDecisionField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string show {
        get {
            return this.showField;
        }
        set {
            this.showField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string displayMode {
        get {
            return this.displayModeField;
        }
        set {
            this.displayModeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class RuleXpressPublicationLayoutItemQualityItemUsedByFactSymbol {
    
    private string showField;
    
    private string displayModeField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string show {
        get {
            return this.showField;
        }
        set {
            this.showField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string displayMode {
        get {
            return this.displayModeField;
        }
        set {
            this.displayModeField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class RuleXpressPublicationContent {
    
    private RuleXpressPublicationContentCommunity[] communityField;
    
    private Term[] termField;
    
    private Rule[] ruleField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Community", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public RuleXpressPublicationContentCommunity[] Community {
        get {
            return this.communityField;
        }
        set {
            this.communityField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Term")]
    public Term[] Term {
        get {
            return this.termField;
        }
        set {
            this.termField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("Rule")]
    public Rule[] Rule {
        get {
            return this.ruleField;
        }
        set {
            this.ruleField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
public partial class RuleXpressPublicationContentCommunity {
    
    private string idField;
    
    private string signifierField;
    
    private string descriptionField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string ID {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string signifier {
        get {
            return this.signifierField;
        }
        set {
            this.signifierField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAttributeAttribute()]
    public string description {
        get {
            return this.descriptionField;
        }
        set {
            this.descriptionField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
[System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
public partial class NewDataSet {
    
    private object[] itemsField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("AppliesToDecision", typeof(AppliesToDecision))]
    [System.Xml.Serialization.XmlElementAttribute("DerivedByDecision", typeof(DerivedByDecision))]
    [System.Xml.Serialization.XmlElementAttribute("DerivedByDecisionTable", typeof(DerivedByDecisionTable))]
    [System.Xml.Serialization.XmlElementAttribute("DerivedByRule", typeof(DerivedByRule))]
    [System.Xml.Serialization.XmlElementAttribute("DerivesFact", typeof(DerivesFact))]
    [System.Xml.Serialization.XmlElementAttribute("DerivesTerm", typeof(DerivesTerm))]
    [System.Xml.Serialization.XmlElementAttribute("ItemProperties", typeof(ItemProperties))]
    [System.Xml.Serialization.XmlElementAttribute("Rule", typeof(Rule))]
    [System.Xml.Serialization.XmlElementAttribute("RuleXpressPublication", typeof(RuleXpressPublication))]
    [System.Xml.Serialization.XmlElementAttribute("Term", typeof(Term))]
    [System.Xml.Serialization.XmlElementAttribute("TermRef", typeof(TermRef), IsNullable=true)]
    [System.Xml.Serialization.XmlElementAttribute("Text", typeof(Text), IsNullable=true)]
    [System.Xml.Serialization.XmlElementAttribute("UsedByDecision", typeof(UsedByDecision))]
    [System.Xml.Serialization.XmlElementAttribute("UsedByDecisionTable", typeof(UsedByDecisionTable))]
    [System.Xml.Serialization.XmlElementAttribute("UsedByFact", typeof(UsedByFact))]
    [System.Xml.Serialization.XmlElementAttribute("UsedByNeighborhood", typeof(UsedByNeighborhood))]
    [System.Xml.Serialization.XmlElementAttribute("UsedByRule", typeof(UsedByRule))]
    [System.Xml.Serialization.XmlElementAttribute("UsedByRuleGroup", typeof(UsedByRuleGroup))]
    [System.Xml.Serialization.XmlElementAttribute("UsedByTerm", typeof(UsedByTerm))]
    [System.Xml.Serialization.XmlElementAttribute("UsesDecisionTable", typeof(UsesDecisionTable))]
    [System.Xml.Serialization.XmlElementAttribute("UsesFact", typeof(UsesFact))]
    [System.Xml.Serialization.XmlElementAttribute("UsesFactSymbol", typeof(UsesFactSymbol))]
    [System.Xml.Serialization.XmlElementAttribute("UsesRule", typeof(UsesRule))]
    [System.Xml.Serialization.XmlElementAttribute("UsesRuleGroup", typeof(UsesRuleGroup))]
    [System.Xml.Serialization.XmlElementAttribute("UsesTerm", typeof(UsesTerm))]
    public object[] Items {
        get {
            return this.itemsField;
        }
        set {
            this.itemsField = value;
        }
    }
}
